name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  quality:
    uses: and3rn3t/.github/.github/workflows/reusable-node-verify.yml@bac71674cf57c550774f71a70e32a5bb7bec48ad # v1
    with:
      command: npm run check-all && npm run build
